image: docker

stages:
  - tests
  - deploy

before_script:
  - echo "before script running..."

test:
  stage: tests
  script:
    - echo "tests stage"
    - python -m pytest
    - docker build -t api .
    - docker run api

deploy:
  stage: deploy
  script:
    - echo "deploy stage"
