image: docker

stages:
  - test
  - deploy

before_script:
  - echo "before script running..."

test:
  stage: test
  script:
    - echo "test stage"
    - docker build -t api .
    - docker run api

deploy:
  stage: deploy
  script:
    - echo "deploy stage"
